name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc make

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -j

      - name: Test
        run: ctest --test-dir build --output-on-failure

      - name: Smoke run
        run: |
          ./build/pqc_cli info --alg mlkem-ref
          ./build/pqc_cli benchmark --alg mlkem-ref --iterations 50 --out bench_result.csv

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2 + MinGW
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make

      - name: Configure
        run: cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_C_COMPILER=gcc

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure

      - name: Smoke run
        run: |
          ./build/pqc_cli.exe info --alg mlkem-ref
          ./build/pqc_cli.exe benchmark --alg mlkem-ref --iterations 50 --out bench_result.csv
